# Generated by Django 3.2 on 2022-04-10 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read_by',
            field=models.ManyToManyField(default=[], related_name='messages_read_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
