# Generated by Django 3.2 on 2022-04-10 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_alter_message_read_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read_by',
            field=models.ManyToManyField(default=list, related_name='messages_read_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
